### Test Cron Apagado con CPU personalizado
@token = <TU_TOKEN>

GET https://kamatera-birwqvszx-jmauas-projects.vercel.app/api/cron/apagado?cpu=12
token: {{token}}

### Test Cron Apagado con CPU por defecto (8T)
GET https://kamatera.vercel.app/api/cron/apagado

### Test Cron Apagado con otro valor de CPU
GET https://kamatera.vercel.app/api/cron/apagado?cpu=8T
